# Generated by Django 5.1.4 on 2025-01-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trade_code', models.CharField(max_length=50)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open_a', models.FloatField(db_column='open')),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'verbose_name': 'StockMarketData',
                'verbose_name_plural': 'StockMarketDatas',
            },
        ),
    ]
