# Generated by Django 5.1.4 on 2025-01-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarketdata',
            name='volume',
            field=models.FloatField(),
        ),
    ]
